# Generated by Django 4.2.7 on 2023-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default='none'),
        ),
    ]
